/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import biblioteca.Administrador;

/**
 *
 * @author walis
 */
public class TelaADM extends javax.swing.JFrame {

    /**
     * Creates new form IniciarV
     * @param adm
     */
    public TelaADM(Administrador adm) {
        initComponents();
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        procurarTela = new javax.swing.JButton();
        adicionarLivroTela = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        atualizarLivroTela = new javax.swing.JButton();
        emprestarLivroTela = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        devolverLivroTela = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        procurarTela.setText("Procurar Livro");
        procurarTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procurarTelaActionPerformed(evt);
            }
        });
        getContentPane().add(procurarTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 140, -1));

        adicionarLivroTela.setText("Adicionar livro");
        adicionarLivroTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarLivroTelaActionPerformed(evt);
            }
        });
        getContentPane().add(adicionarLivroTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 140, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Olá! Selecione uma das opções abaixo para prosserguirmos ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 25, -1, 60));

        atualizarLivroTela.setText("Atualizar Livro");
        atualizarLivroTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarLivroTelaActionPerformed(evt);
            }
        });
        getContentPane().add(atualizarLivroTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 140, -1));

        emprestarLivroTela.setText("Emprestar livro");
        emprestarLivroTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestarLivroTelaActionPerformed(evt);
            }
        });
        getContentPane().add(emprestarLivroTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 140, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 273, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 167, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 388, -1, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 388, -1, -1));

        devolverLivroTela.setText("Devolver livro");
        devolverLivroTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverLivroTelaActionPerformed(evt);
            }
        });
        getContentPane().add(devolverLivroTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 140, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 296, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void procurarTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procurarTelaActionPerformed
        // TODO add your handling code here:
        Procurar p = new Procurar();
        p.setVisible(true);
    }//GEN-LAST:event_procurarTelaActionPerformed

    private void adicionarLivroTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarLivroTelaActionPerformed
        // TODO add your handling code here
        Adicionar a = new Adicionar();
        a.setVisible(true);
    }//GEN-LAST:event_adicionarLivroTelaActionPerformed

    private void atualizarLivroTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarLivroTelaActionPerformed
        // TODO add your handling code here:
        Atualizar a = new Atualizar();
        a.setVisible(true);
    }//GEN-LAST:event_atualizarLivroTelaActionPerformed

    private void emprestarLivroTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestarLivroTelaActionPerformed
        // TODO add your handling code here:
        RealizarEmprestimo re = new RealizarEmprestimo();
        re.setVisible(true);       
        
    }//GEN-LAST:event_emprestarLivroTelaActionPerformed

    private void devolverLivroTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverLivroTelaActionPerformed
        // TODO add your handling code here:
        DevolverEmprestimos de = new DevolverEmprestimos();
        de.setVisible(true);
    }//GEN-LAST:event_devolverLivroTelaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarLivroTela;
    private javax.swing.JButton atualizarLivroTela;
    private javax.swing.JButton devolverLivroTela;
    private javax.swing.JButton emprestarLivroTela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton procurarTela;
    // End of variables declaration//GEN-END:variables
}
